# Generated by Django 4.0.2 on 2022-03-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='descriptions',
            field=models.TextField(default=1, max_length=120, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='title',
            field=models.CharField(default='', max_length=120, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
