# Generated by Django 4.0.2 on 2022-03-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_good_descriptions_good_slug_good_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='title',
            field=models.CharField(default='', max_length=120, verbose_name='Название'),
        ),
    ]
