# Generated by Django 4.0.2 on 2022-03-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_good_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='kind',
            field=models.CharField(default='', max_length=120, verbose_name='Название'),
        ),
    ]
