# Generated by Django 4.0.2 on 2022-03-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_good_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='kind',
            field=models.CharField(default='', max_length=120, verbose_name='Тип'),
        ),
    ]
