# Generated by Django 4.0.2 on 2022-04-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_good_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='cost',
            field=models.CharField(default='', max_length=120, verbose_name='Название'),
        ),
    ]
