# Generated by Django 4.0.2 on 2022-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_good_dimensions_good_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='dimensions',
            field=models.CharField(default='', max_length=120, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='good',
            name='material',
            field=models.CharField(default='', max_length=120, verbose_name='Материал'),
        ),
    ]
