# Generated by Django 4.0.2 on 2022-04-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options_alter_cart_author_alter_cart_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='choose_color',
            field=models.CharField(choices=[('black', 'black'), ('green', 'green'), ('red', 'red'), ('yelow', 'yelow'), ('blue', 'blue')], default='black', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cost',
            field=models.CharField(default='', max_length=100, verbose_name='Товар'),
        ),
    ]
