# Generated by Django 4.0.2 on 2022-04-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_choose_color_cart_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='goods_images'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cost',
            field=models.CharField(default='0', max_length=100, verbose_name='Стоимость'),
        ),
    ]
