# Generated by Django 4.0.2 on 2022-04-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_img_alter_cart_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='img',
        ),
    ]
