# Generated by Django 4.0.2 on 2022-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='goods_images'),
        ),
    ]
